### ISSUE TITLE
Figure out SIMD types

### ISSUE THREAD

**Issue by keynmol** [indoorvivants/sn-bindgen#160]
For a header file like this:

```c
typedef float __m128 __attribute__((__vector_size__(16), __aligned__(16)));

struct MyStuff {
  __m128 x;
};
```

we currently get an uninformative crash:

```scala
~/p/sn-bindgen (main) > bin/bindgen --package hello --header test-sse.h --scala
[bindgen] info Using clang available in PATH, with following info
      Ubuntu clang version 14.0.0-1ubuntu1
      Target: x86_64-pc-linux-gnu
      Thread model: posix
      InstalledDir: /usr/bin
      Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
      Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
      Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
      Candidate multilib: .;@m64
      Selected multilib: .;@m64
[bindgen] info Using following clang flags
      -I/usr/lib/llvm-14/lib/clang/14.0.0/include
      -I/usr/local/include
      -I/usr/include/x86_64-linux-gnu
      -I/usr/include
[bindgen] warn Unknown type: Kind: Vector, full type: __attribute__((__vector_size__(4 * sizeof(float)))) float
scala.MatchError: Void (of class bindgen.CType$$anon$1)
        at java.lang.StackTrace$.currentStackTrace(Unknown Source)
        at java.lang.Throwable.fillInStackTrace(Unknown Source)
        at bindgen.rendering.sizes_and_alignments$package$.alignment(Unknown Source)
        at bindgen.rendering.sizes_and_alignments$package$.offsets$$anonfun$1(Unknown Source)
        at bindgen.rendering.sizes_and_alignments$package$$$Lambda$1.apply(Unknown Source)
        at scala.collection.immutable.List.map(Unknown Source)
        at bindgen.rendering.sizes_and_alignments$package$.offsets(Unknown Source)
        at bindgen.rendering.struct$package$.struct(Unknown Source)
        at bindgen.rendering.binding$package$.renderStructs$$anonfun$1$$anonfun$1(Unknown Source)
        at bindgen.rendering.binding$package$$$Lambda$34.applyVoid(Unknown Source)
        at scala.runtime.function.JProcedure2.apply(Unknown Source)
        at bindgen.rendering.binding$package$.renderAll$$anonfun$1(Unknown Source)
        at bindgen.rendering.binding$package$$$Lambda$23.apply(Unknown Source)
        at scala.collection.immutable.List.foreach(Unknown Source)
        at bindgen.rendering.binding$package$.renderAll(Unknown Source)
        at bindgen.rendering.binding$package$.renderStructs$$anonfun$1(Unknown Source)
        at bindgen.rendering.binding$package$$$Lambda$21.applyVoid(Unknown Source)
        at scala.runtime.function.JProcedure1.apply(Unknown Source)
        at bindgen.rendering.utils$package$.nestIf(Unknown Source)
        at bindgen.rendering.binding$package$.renderStructs(Unknown Source)
        at bindgen.rendering.binding$package$.binding(Unknown Source)
        at bindgen.Generate$.main$$anonfun$1(Unknown Source)
        at bindgen.Generate$$$Lambda$1.applyVoid(Unknown Source)
        at scala.runtime.function.JProcedure1.apply(Unknown Source)
        at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
        at bindgen.Generate$.main(Unknown Source)
        at bindgen.Generate.main(Unknown Source)
        at <none>.main(Unknown Source)
        at <none>.(Unknown Source)
        at <none>.__libc_start_main(Unknown Source)
        at <none>._start(Unknown Source)
```

**Comment by keynmol** [comment]
FWIW, the latest version no longer crashes, because we cheat and just find a type that has the correct size:

```scala
package hello

import _root_.scala.scalanative.unsafe.*
import _root_.scala.scalanative.unsigned.*
import _root_.scala.scalanative.libc.*
import _root_.scala.scalanative.*

object aliases:
  import _root_.hello.aliases.*
  import _root_.hello.structs.*

  /**
   * [bindgen] header: test-sse.h
  */
  opaque type __m128 = CStruct4[Float, Float, Float, Float]
  object __m128:
    given _tag: Tag[__m128] = Tag.materializeCStruct4Tag[Float, Float, Float, Float]
    inline def apply(inline o: CStruct4[Float, Float, Float, Float]): __m128 = o
    extension (v: __m128)
      inline def value: CStruct4[Float, Float, Float, Float] = v

object structs:
  import _root_.hello.aliases.*
  import _root_.hello.structs.*

  /**
   * [bindgen] header: test-sse.h
  */
  opaque type MyStuff = CStruct1[__m128]
  object MyStuff:
    given _tag: Tag[MyStuff] = Tag.materializeCStruct1Tag[__m128]
    def apply()(using Zone): Ptr[MyStuff] = scala.scalanative.unsafe.alloc[MyStuff](1)
    def apply(x : __m128)(using Zone): Ptr[MyStuff] =
      val ____ptr = apply()
      (!____ptr).x = x
      ____ptr
    extension (struct: MyStuff)
      def x : __m128 = struct._1
      def x_=(value: __m128): Unit = !struct.at1 = value

object types:
  export _root_.hello.structs.*
  export _root_.hello.aliases.*

object all:
  export _root_.hello.aliases.__m128
  export _root_.hello.structs.MyStuff
```

It's not a solution I'm happy with, but I will return back to it once it actually causes a problem.
