### ISSUE TITLE
scala.MatchError: CType.IncompleteArray

### ISSUE THREAD

**Issue by vbergeron** [indoorvivants/sn-bindgen#223]
**Context**
I am trying to generate bindings on the postgres _server_ headers, in order to create extensions using scala native.

**Setup**
Grab the postgres server headers (on debian, there is the `postgresql-server-dev-XX` package where XX is the major version).
Create an amalgam file desribed below.
```c
typedef unsigned long int uintptr_t; //  ¯\_(ツ)_/¯ 
#include "postgres.h"
#include "fmgr.h"
```

bindgen config :

```scala
import bindgen.interface.Binding

bindgenBindings := {

  val basedir = baseDirectory.value / "include"

  val postgres = basedir / "postgresql" / "13" / "server"

  Seq(
    Binding
      .builder(postgres / "postgres-amalgam.h", "PG13")
      .withClangFlags(List("-I" + postgres))
      .withCImports(List("stdbool.h", "stdint.h"))
      .build
  )
}
```

Bindgen output : 
```
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn clang: warning: 'format' attribute argument not supported: gnu_printf
[bindgen] warn Unknown type: Kind: Int128, full type: __int128
[bindgen] warn Unknown type: Kind: UInt128, full type: unsigned __int128
[bindgen] warn Struct 'BpChar' has a Flexible Array Member, so it was dropped from the definition. See https://github.com/indoorvivants/sn-bindgen/issues/62 for details
[bindgen] warn Struct 'FunctionCallInfoBaseData' has a Flexible Array Member, so it was dropped from the definition. See https://github.com/indoorvivants/sn-bindgen/issues/62 for details
[bindgen] warn Struct 'VarChar' has a Flexible Array Member, so it was dropped from the definition. See https://github.com/indoorvivants/sn-bindgen/issues/62 for details
[bindgen] warn Struct 'bytea' has a Flexible Array Member, so it was dropped from the definition. See https://github.com/indoorvivants/sn-bindgen/issues/62 for details
[bindgen] warn Struct 'int2vector' has a Flexible Array Member, so it was dropped from the definition. See https://github.com/indoorvivants/sn-bindgen/issues/62 for details
[bindgen] warn Struct 'oidvector' has a Flexible Array Member, so it was dropped from the definition. See https://github.com/indoorvivants/sn-bindgen/issues/62 for details
[bindgen] warn Struct 'text' has a Flexible Array Member, so it was dropped from the definition. See https://github.com/indoorvivants/sn-bindgen/issues/62 for details
[bindgen] warn Struct 'varattrib_1b' has a Flexible Array Member, so it was dropped from the definition. See https://github.com/indoorvivants/sn-bindgen/issues/62 for details
[bindgen] warn Struct 'varattrib_1b_e' has a Flexible Array Member, so it was dropped from the definition. See https://github.com/indoorvivants/sn-bindgen/issues/62 for details
[bindgen] warn Struct 'varlena' has a Flexible Array Member, so it was dropped from the definition. See https://github.com/indoorvivants/sn-bindgen/issues/62 for details
scala.MatchError: CType.IncompleteArray(of = CType.NumericIntegral(base = Char, sign = Signed)) (of class bindgen.CType$IncompleteArray)
	at scala.runtime.function.JProcedure1.apply(Unknown Source)
	at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
	at java.lang.StackTrace$.currentStackTrace(Unknown Source)
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at bindgen.rendering.sizes_and_alignments$package$.staticSize(Unknown Source)
	at bindgen.rendering.sizes_and_alignments$package$.staticSize$$anonfun$1(Unknown Source)
	at bindgen.rendering.sizes_and_alignments$package$.staticSize(Unknown Source)
	at scala.collection.immutable.List.map(Unknown Source)
	at bindgen.rendering.sizes_and_alignments$package$.staticSize(Unknown Source)
	at bindgen.rendering.scalaType$package$.scalaType(Unknown Source)
	at bindgen.rendering.union$package$.union(Unknown Source)
	at bindgen.rendering.binding$package$.renderAll$$anonfun$1(Unknown Source)
	at scala.collection.immutable.List.foreach(Unknown Source)
	at bindgen.rendering.binding$package$.renderAll(Unknown Source)
	at bindgen.rendering.binding$package$.renderUnions$$anonfun$1(Unknown Source)
	at bindgen.rendering.binding$package$$$Lambda$29.applyVoid(Unknown Source)
	at scala.runtime.function.JProcedure1.apply(Unknown Source)
	at bindgen.rendering.binding$package$.renderUnions(Unknown Source)
	at bindgen.rendering.binding$package$.binding(Unknown Source)
	at bindgen.Generate$.main$$anonfun$1(Unknown Source)
	at scala.runtime.function.JProcedure1.apply(Unknown Source)
	at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
	at <none>.main(Unknown Source)
	at <none>.__libc_start_main(Unknown Source)
	at <none>._start(Unknown Source)
```

**Comment by keynmol** [comment]
Minimisation:

```c
typedef union {
  struct 
  {
    int va_header;
    char va_data[]; 
  } va_compressed;
} varattrib_4b;
```

`union` seems to be the one causing problems here.
