### ISSUE TITLE
[high] Non-deterministic failures

### ISSUE THREAD

**Issue by keynmol** [indoorvivants/sn-bindgen#57]
There's a very annoying problem that manifests itself randomly on different platforms and different setups.

```
java.lang.ClassCastException: scala.scalanative.unsigned.ULong cannot be cast to bindgen.Binding
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at scala.scalanative.runtime.package$.throwClassCast(Unknown Source)
	at bindgen.analyse$package$.analyse$$anonfun$5(Unknown Source)
	at <none>.(Unknown Source)
	at <none>.(Unknown Source)
	at <none>.(Unknown Source)
	at <none>.(Unknown Source)
	at <none>.clang_visitChildren(Unknown Source)
	at <none>.(Unknown Source)
	at bindgen.analyse$package$.analyse(Unknown Source)
	at bindgen.Generate$.main$$anonfun$1(Unknown Source)
	at bindgen.Generate$$$Lambda$1.applyVoid(Unknown Source)
	at scala.runtime.function.JProcedure1.apply(Unknown Source)
	at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
	at <none>.main(Unknown Source)
	at <none>.__libc_start_main(Unknown Source)
	at <none>._start(Unknown Source)
```

```
java.lang.ClassCastException: scala.scalanative.unsigned.ULong cannot be cast to bindgen.Binding
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at scala.scalanative.runtime.package$.throwClassCast(Unknown Source)
	at bindgen.analyse$package$.analyse$$anonfun$5(Unknown Source)
	at <none>.special_visitor(Unknown Source)
	at <none>._ZN5clang8cxcursor13CursorVisitor5VisitE8CXCursorb(Unknown Source)
	at <none>._ZN5clang8cxcursor13CursorVisitor17VisitFunctionDeclEPNS_12FunctionDeclE(Unknown Source)
	at <none>._ZN5clang8cxcursor13CursorVisitor13VisitChildrenE8CXCursor(Unknown Source)
	at <none>._ZN5clang8cxcursor13CursorVisitor23handleDeclForVisitationEPKNS_4DeclE(Unknown Source)
	at <none>._ZN5clang8cxcursor13CursorVisitor16VisitDeclContextEPNS_11DeclContextE(Unknown Source)
	at <none>._ZN5clang8cxcursor13CursorVisitor13VisitChildrenE8CXCursor(Unknown Source)
	at <none>.clang_visitChildren(Unknown Source)
	at <none>.wrap_visitChildren(Unknown Source)
	at bindgen.analyse$package$.analyse(Unknown Source)
	at bindgen.Generate$.main$$anonfun$1(Unknown Source)
	at bindgen.Generate$$$Lambda$1.applyVoid(Unknown Source)
	at scala.runtime.function.JProcedure1.apply(Unknown Source)
	at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
	at <none>.main(Unknown Source)
```

One thing that seems to be constant is that it occurs in the glue visitor: https://github.com/indoorvivants/sn-bindgen/blob/main/libclang/src/main/resources/scala-native/clang.c#L39-L44

I think we need to run this with AddressSanitizer, as it seems to be accessing wrong memory

**Comment by keynmol** [comment]
1. Attempting to add AddressSanitizer was not successful - it barks at heap allocations, which I believe is a false positive
2. I most frequently see this issue with `closure.h` test file, and on MacOS. As a stab in the dark, I changed deep closure recursion to tail recursive calls: https://github.com/indoorvivants/sn-bindgen/pull/67 and will monitor from there whether it has any effect
